login_demo/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from django.urls import path
from myapp import views
app_name="myapp"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("myapp.urls")),
    path('',views.home,name="home"),
    path('register/',views.register,name="register"),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='user_logout'),
    path('profile/',views.profile,name="profile"),
    path('reset_password/',views.reset_password,name="reset_password"),
    path('frgt/',views.frgt_pwd,name="frgt"),
    path('frgt/<id>',views.res_pwd,name="res_pwd"),
]

myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"
urlpatterns = [
    path('',views.home,name="home"),
    path('register/',views.register,name="register"),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='user_logout'),
    path('profile/',views.profile,name="profile"),
    path('reset_password/',views.reset_password,name="reset_password"),
    path('frgt/',views.frgt_pwd,name="frgt"),
    path('frgt/<id>',views.res_pwd,name="res_pwd"),

]

myapp/models.py
from django.db import models

# Create your models here.

myapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
class RegistrationForm(forms.ModelForm):
    password=forms.CharField(max_length=100,required=True,widget=forms.PasswordInput)
    class Meta:
        model=User
        fields=('username','password','email')


class PasswordResetForm(forms.Form):
    password=forms.CharField(max_length=100,required=True,label="New Password :",widget=forms.PasswordInput)
    confirm=forms.CharField(max_length=100,required=True,label=" Confirm Password :",widget=forms.PasswordInput)
    
    def clean(self):
        cleaned_data=super().clean()
        if cleaned_data.get('password')!=cleaned_data.get('confirm'):
            raise ValidationError("Passwords Not Matched")
        return cleaned_data

myapp/views.py
from django.shortcuts import render,redirect
from myapp.forms import RegistrationForm,PasswordResetForm
from django.contrib.auth.models import User
# Create your views here.
def home(request):
    return render(request,"myapp/home.html")

def register(request):
    if request.method=='POST':
        form=RegistrationForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
        else:
            return render(request,"myapp/register.html",{'form':form})
    form=RegistrationForm()
    return render(request,"myapp/register.html",{'form':form})

from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required
def user_login(request):
    if request.method=="POST":
        username=request.POST.get("uname")
        pwd=request.POST.get('pwd')
        user=authenticate(request,username=username,password=pwd)
        if user:
            if user.is_active:
                login(request,user)
                return redirect('myapp:home')
        else:
            return redirect('myapp:home')
    return render(request,'myapp/user_login.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect('myapp:home')

@login_required(login_url='/login/')
def profile(request):
    return render(request,"myapp/profile.html")

@login_required(login_url='/login/')
def reset_password(request):
    form=PasswordResetForm()
    if request.method=="POST":
        form=PasswordResetForm(request.POST)
        if form.is_valid():
            password=form.cleaned_data.get('password')
            request.user.set_password(password)
            request.user.save()
        else:
            return render(request,'myapp/forgot_password.html',{'form':form})
    return render(request,'myapp/forgot_password.html',{'form':form})

from django.core.mail import send_mail

def frgt_pwd(request):
    if request.method=="POST":
        username=request.POST['username']
        user=User.objects.get(username=username)
        link="http://127.0.0.1:8000/frgt/{}".format(user.id)
        send_mail("Password Reset Link",
        "click on the link to reset password\n"+link,
        "akshay.python@gmail.com",
        (user.email,),
        fail_silently=False)
    return render(request,"myapp/frgtpwd.html")

def res_pwd(request,id):
    form=PasswordResetForm()
    if request.method=="POST":
        form=PasswordResetForm(request.POST)
        if form.is_valid():
            password=form.cleaned_data.get('password')
            user=User.objects.get(id=id)
            user.set_password(password)
            user.save()
        else:
            return render(request,'myapp/forgot_passsword.html',{'form':form})
    return render(request,'myapp/forgot_password.html',{'form':form})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    {% block title %}
    <title>BASE Page</title>
    {% endblock %}
</head>
<body>
    {% include "partials/_navbar.html" %}
    {% block content %}
    <div class="jumbotron">
        <h1> BASE PAGE</h1>
    </div>
    {% endblock %}
</body>
</html>

templates/myapp/forgot_password.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
  <title>Reset Password</title>
{% endblock %}

{% block content %}
  <div class="jumbotron">
<center>
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Change Password" class='btn btn-primary'>
    </form>
</center>
  </div>
{% endblock %}

templates/myapp/frgtpwd.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
  <title>Forgot Password</title>
{% endblock %}

{% block content %}
  <div class="jumbotron">
      
      <center>
        <h4>After Submitting Check Your Mail For Reset Link</h4>
          <form method="POST">
              {% csrf_token %}
              <label for="username">User Name : </label>
              <input type="text" name="username" id="username" required>
              <input type="submit" value="Submit" class="btn btn-primary">
          </form>
      </center>
  </div>
{% endblock %}

templates/myapp/home.html
{% extends "base.html" %}

{% block title %}
  <title>Home Page</title>
{% endblock %}

{% block content %}
<div class="jumbotron">
    
    <h1>Home PAGE</h1>
    {% if user.is_authenticated %}
    <h2>Welcome Miss. {{user.username}}</h2>      
    
    {% endif %}
    
</div>
{% endblock %}

templates/myapp/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
<title>{{user.username}} | Profile</title>  
{% endblock %}

{% block content %}
  <div class="jumbotron">
      <h2>Find Your Details Below!!!</h2>
      <br>
        <h3>UserName  :  {{user.username}}</h3>
        <h3>Email     :  {{user.email}}</h3>
  </div>
{% endblock %}

templates/myapp/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
  <title>Registration Page</title>
{% endblock %}

{% block content %}
  <h2>Please Fill The Form...</h2>
  <form method="POST">
      {% csrf_token %}
      {{form|crispy}}
      <input type="submit" value="Register" class="btn btn-primary">
  </form>
{% endblock %}

templates/myapp/user_login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
  <title>Login Page</title>
{% endblock %}

{% block content %}
  <center>
    <form method="POST">
      {% csrf_token %}
        <div class="form-group">
          <label for="exampleInputEmail1">UserName</label>
          <input type="text" class="form-control" name="uname" id="exampleInputEmail1" aria-describedby="emailHelp">
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" name="pwd" id="exampleInputPassword1">
        </div>
        <a href="{% url 'myapp:frgt' %}">Forgot Password?</a>
      <input type="submit" value="Login" class="btn btn-primary">
  </form>
  </center>
{% endblock %}

templates/partials/_navbar.html
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'myapp:home' %}">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'myapp:register' %}">Register User</a>
  </li>
  {% if user.is_authenticated %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'myapp:profile' %}">Profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'myapp:reset_password' %}">Change Password</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'myapp:user_logout' %}">Logout</a>
  </li>
    <form method="GET">
      <input type="text" name="username" id="username" placeholder="User Search">
      <input type="submit" value="Search" class="btn btn-primary">
    </form>
  {% else %}
  <li class="nav-item">
  <a class="nav-link" href="{% url 'myapp:login' %}">Login</a>
  </li>
  {% endif %}
</ul>